---
apiVersion: v1
kind: Service
metadata:
  name: codecharta-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    tier: web
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
    tier: web
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
